### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by psifertex** [zznop/bnida#22]
This plugin currently does not list plugin3 compatibility in the plugin.json. If it is compatible with python3, please update the plugin.json and submit a new release for the plugin manager.

If the plugin isn't actually compatible yet, please consider adding python3 support. 

Binary Ninja will be requiring all plugins to be compatible with python3 and will remove plugins that only support python2 from the plugin manager at some point.

Thanks!

**Comment by zznop** [comment]
https://github.com/zznop/bnida/releases/tag/1.2

**Comment by psifertex** [comment]
🔥

Added, thanks!
